### ISSUE TITLE
Error running Uni-pKa

### ISSUE THREAD

**Issue by yipy0005** [dptech-corp/Uni-pKa#2]
Hi! I was trying to do pKa prediction and found this very good work, and I was very interested to try it out. When I tried `python main.py enum -i ../test.csv -o test.out -m B`,  I had the following error:

Reconstructing ../test.csv with the template smarts_pattern.tsv from B microstates
`100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.27it/s]
Traceback (most recent call last):
  File "/home/user/GitHub/Uni-pKa/enumerator/main.py", line 480, in <module>
    enum_dataset(
  File "/home/user/GitHub/Uni-pKa/enumerator/main.py", line 455, in enum_dataset
    dataset[["SMILES", "TARGET", "ref."]].to_csv(output_file, sep="\t")
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniforge3/envs/unipka/lib/python3.11/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniforge3/envs/unipka/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/user/miniforge3/envs/unipka/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6179, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['TARGET', 'ref.'] not in index"`

Could you provide me with an example of the input CSV file to run Uni-pKa with? :)
[test.csv](https://github.com/dptech-corp/Uni-pKa/files/14617581/test.csv)

**Comment by Benzoin96485** [comment]
I'm so sorry for a late reply. I've noticed this and will come back to it soon.

**Comment by Benzoin96485** [comment]
Now Fixed! This error is because we used to assume that the data has labels and references, which doesn't apply to custom datasets. Now the enumerator only requires the SMILES column. Thank you for your feedback!
